#!/bin/env ruby
# coding: utf-8
require 'simplecov'

SimpleCov.start do
	filters.clear
	add_filter { |file| not file.filename.start_with?(Dir.pwd.split('/')[0..-2].join('/')) }
#	add_filter { |file| file.filename =~ /.gem/ }
	use_merging true
	command_name "process_#{$$}"
end

require_relative 'seapig-server.rb'
